// Regenerates src/Catalog.js from catalog.tsv (section, level, url, title)
const fs = require('fs');
const path = require('path');
const rows = fs.readFileSync(path.join(__dirname, 'catalog.tsv'), 'utf8').trim().split(/\r?\n/);
const cat = {};
const decode = s => s.replace(/&amp;/g, '&').replace(/&#8217;|&#039;/g, "'").replace(/&quot;/g, '"');
const clean = t => decode(t)
  .replace(/\s+[–-]\s+(A1|A2|B1\+?|B2|C1)\b.*$/i, '')
  .replace(/\s+[–-]\s+.*(English|writing|listening|reading).*$/i, '')
  .trim();
for (const r of rows) {
  const [sec, lvl, url, title] = r.split('\t');
  const key = sec === 'grammar-points' ? 'grammar' : sec;
  ((cat[key] = cat[key] || {})[lvl] = cat[key][lvl] || []).push({ t: clean(title), u: url });
}
fs.writeFileSync(path.join(__dirname, 'src', 'Catalog.js'),
  '// Generated by gen-catalog.js from test-english.com index pages. Do not edit by hand.\n' +
  'var CATALOG = ' + JSON.stringify(cat, null, 0).replace(/\],"/g, '],\n"') + ';\n');
console.log(Object.keys(cat).map(k => k + ':' + Object.values(cat[k]).flat().length).join(' '));
